### ISSUE TITLE
Add list of references on an issue

### ISSUE THREAD

**Issue by gdscei** [huboard/huboard#316] opened 2014-04-06 11:03 UTC
In GitHub's issue view, you can see where the issue is being referenced (other issues, commits). It would be nice if this was available in HuBoard too.

**Comment by ehausen** [comment] 2015-07-02 15:56
I think this is a duplicate of #454 which seem to be given a milestone but it is blocked

Maybe you guys can vote there and thsi can be closed?

**Comment by discorick** [comment] 2015-10-21 13:29
closed by #454

**Comment by dahlbyk** [comment] 2016-04-15 17:14
Closing in deference to #454

**Closed by dahlbyk** 2016-04-15 17:14 UTC
Labels: 4 - Deployed
