### ISSUE TITLE
Search in full name for mentions as well 

### ISSUE THREAD

**Issue by stof** [huboard/huboard#442] opened 2014-11-20 11:16 UTC
On github, the mention autocompleter searches both in the username and the full name, and it displays the full name near the username. On huboard, only the username is taken into account. This makes it harder to find the people we want to mention

**Comment by benjamincharity** [comment] 2015-09-30 13:45
Looks like API limitations.. https://github.com/rauhryan/huboard/issues/581

**Comment by dahlbyk** [comment] 2016-04-15 17:41
Closing as duplicate of #581

**Closed by dahlbyk** 2016-04-15 17:41 UTC
Labels: 4 - Deployed
