### ISSUE TITLE
Multiple assignee on issue

### ISSUE THREAD

**Issue by petey-rock** [huboard/huboard#672] opened 2016-06-03 21:01 UTC
#### Description: 
With the addition of GitHub supporting multiple assignees, cards should lists all issues someone is assigned to even though another person is assigned to the issue.

#### Notes:
hello@petrisandstrom.com-

> Feedback: GitHub now supports multiple assignee on an issue. Would love to have all my issues listed when I filter my issues on HuBoard even though someone else is on the issue as well.
> 
> The assignees are ordered in alphabetical order and only the first one gets the issue on HuBoard.

Related to #612

**Comment by dahlbyk** [comment] 2016-06-03 21:06
@petey-rock do you want to keep this around or can we close as duplicate of #612 and add a note that we need to make sure filters work as expected?

**Comment by petey-rock** [comment] 2016-06-07 20:25
@dahlbyk Yeah we can kill this one and make a note on #612

**Closed** 2016-06-07 20:26 UTC
Labels: 1 - Next release, Feature Request
