### ISSUE TITLE
Important display problems since we installed HB:E v1.6.107

### ISSUE THREAD

**Issue by patdolem** [huboard/huboard#631] opened 2016-02-05 21:27 UTC
We are experiencing the following problems:
- [ ] Tasks columns display is not fitting the screen
- [ ] Columns width are not always the same (this cause the problem above)
- [ ] The X that was visible on a filter when selected is not anymore displayed

We'll have to roll-out to the previous release as these display problems are too much disrupting unless this can be fixed asap.

**Comment by patdolem** [comment] 2016-02-05 21:31
Adding some screenshots:
This screenshot shows it's not fitting the screen (the Done column is not visible)
![display issue 1](https://devtopia.esri.com/github-enterprise-assets/0000/0014/0004/4150/5e5df93a-cc0c-11e5-94e3-85d7888e37d7.png)

This screenshot shows a fit in the screen but the backlog and Done column are larger than the others.nother
![display issue 2](https://devtopia.esri.com/github-enterprise-assets/0000/0014/0004/4151/62f69326-cc0c-11e5-82cb-f401a526773e.png)

**Comment by patdolem** [comment] 2016-02-08 21:29
@rauhryan When do you expect the new release to be delivered?

**Comment by rauhryan** [comment] 2016-02-08 21:42
We are having some trouble reproducing the error consistently. 

It's possible that it's a problem with the latest version chrome.

Once we can nail it down it's very simple to package up a new release.

@discorick is looking into it today

**Comment by rauhryan** [comment] 2016-02-08 22:13
Screen shot of the fix


![uploads/18b5aee0-e374-499c-a020-9edb6f078081/rauhryan_skipping_stones_repo_HuBoard.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F18b5aee0-e374-499c-a020-9edb6f078081%2Frauhryan_skipping_stones_repo_HuBoard.png)

**Comment by rauhryan** [comment] 2016-02-08 22:40
My team needs to review and accept my PR, I can get a new release built quickly after that.

**Comment by patdolem** [comment] 2016-02-08 22:56
Screen shot looks good. Hope it'll be OK soon. Thanks.

**Comment by dahlbyk** [comment] 2016-02-08 23:15
> The X that was visible on a filter when selected is not anymore displayed

@rauhryan did you have a chance to look into this, too?

**Comment by rauhryan** [comment] 2016-02-08 23:22
> The X that was visible on a filter when selected is not anymore displayed

That was by design, the X was confusing users and made the Dim/Hide functionality

**Comment by rauhryan** [comment] 2016-02-09 01:00
@patdolem - 

I'm building a new package right now

I need to test it locally to make sure everything is good to go, I'll ping you when I get a new version on the portal

**Comment by discorick** [comment] 2016-02-11 15:45
@patdolem We plan to release this to enterprise tomorrow (the current release just needs a little more testing). 

Today is Techstars Demo day, if you are interesting in watching @rauhryan pitch HuBoard, tune into: http://tsta.rs/Y69i7 at 3:00PM CST.

**Comment by seanlinsley** [comment] 2016-02-14 03:08
Are Bountysource and Huboard conflicting with eachother when adding text to the end of tickets?

<img width="718" alt="screen shot 2016-02-13 at 9 08 04 pm" src="https://cloud.githubusercontent.com/assets/688886/13031530/edb5ec48-d295-11e5-8ce4-d6f53d6cbc6d.png">

**Comment by rauhryan** [comment] 2016-02-14 19:15
> Are Bountysource and Huboard conflicting with eachother when adding text to the end of tickets?

I just removed the plugin, hopefully we won't see the double posting anymore

**Comment by dahlbyk** [comment] 2016-02-17 22:51
I just added https://github.com/huboard/huboard-web/issues/205 to more completely document the column width and wrapping issues I'm still seeing in Firefox. Everything seems fine in Chrome.

**Comment by patdolem** [comment] 2016-03-18 20:23
Everything is good for us now. We are using Chrome.

**Comment by rauhryan** [comment] 2016-03-18 20:37
We just fixed it in Firefox as well and should have a new release out soon.

- Ryan

On Fri, Mar 18, 2016 at 3:23 PM, Patrick Dolemieux <notifications@github.com

**Comment by rauhryan** [comment] 2016-03-21 04:33
Just released a hotfix version on the enterprise portal 1.6.115

**Comment by dahlbyk** [comment] 2016-03-25 21:23
@patdolem are we good to close this?

**Comment by patdolem** [comment] 2016-03-25 21:36
@dahlbyk Yes it's good for us. It was already and is still working on Chrome.

**Closed** 2016-03-28 01:52 UTC
Labels: 3 - In Review, Defect, Enterprise, ★★★
