### ISSUE TITLE
Show count in collapsed columns

### ISSUE THREAD

**Issue by ottopaulsen** [huboard/huboard#389] opened 2014-09-02 09:15 UTC
When a column is collapsed, it is impossible to see if there are any issues there. It should be possible to show the count in the header. It would not require more space, I suppose.

**Comment by benjamincharity** [comment] 2015-09-30 13:47
:+1:

**Comment by discorick** [comment] 2015-10-21 13:43
closes #348

**Comment by dahlbyk** [comment] 2016-04-15 17:31
Closing as duplicate of #389

**Closed by dahlbyk** 2016-04-15 17:31 UTC
Labels: 4 - Deployed
